DROP TABLE GENERATED_SCHEMA_HERE.GENERATED_TABLE_NAME_HERE;

( 
    SELECT DISTINCT
        F.NODENAME,
        F.TLEVEL,

        GENERATED_LOOP_HERE

    FROM MAIN_TABLE_NAME_HERE F

    LEFT_JOIN_HERE

    WHERE F.HIEID = HIEID_HERE
);

CREATE TABLE GENERATED_SCHEMA_HERE.GENERATED_TABLE_NAME_HERE AS (

NODE_TEXT_LOOP_HERE
from (
SELECT 	h.*, T.T as node_text,
    SELECT_TEXT_HERE

FROM MAIN_TABLE_QUERY_HERE h
LEFT JOIN (SELECT NODENAME, TXTLG as T from "SCHEMA_NAME_HERE"."RSTHIERNODE"
where
HIEID = HIEID_HERE and LANGU = 'E') T  ON T.NODENAME = h.NODENAME
LEFT_JOIN_TEXT_HERE
) main

);
